# Generated by Django 5.2.9 on 2025-12-20 20:32

from django.db import migrations
from django.contrib.auth import get_user_model

def create_initial_user(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="admin123!"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_article_alter_favorite_user'),
    ]

    operations = [
        migrations.RunPython(create_initial_user),
    ]
